### ISSUE TITLE
Login Page UI Improvement

### ISSUE THREAD

**Issue by Jai-Marothiya** [mohitahlawat2001/aniSensei#11]
# Description

* In the login page Sign button is not properly align and also the opacity is looks quite low, due to which user found difficulty in reading the text. 

![image](https://github.com/user-attachments/assets/d70ad2eb-4a2a-4592-9588-db51df526976)

**Comment by Jai-Marothiya** [comment]
@mohitahlawat2001 please assign this issue to me so that I can fix it.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Jai-Marothiya** [comment]
@mohitahlawat2001 - I raised the PR please take a look.
