### ISSUE TITLE
add ai agent

### ISSUE THREAD

**Issue by mohitahlawat2001** [mohitahlawat2001/aniSensei#2]
like prebuilt prompt to give unique result , like showing tab under search bar ,

**Comment by memyselfandglitch** [comment]
Hello! I would like to work on this issue. In the useAniSensei hook the handleSearch logic is implemented which sends the request to a gemini model. Should I add search prompts under the AniSearchBar that would include some commonly requested queries?

**Comment by mohitahlawat2001** [comment]
yes , add as under search suggestion

**Comment by memyselfandglitch** [comment]
Could you assign this issue to me? Should I get started with the PR?

**Comment by mohitahlawat2001** [comment]
You Should make PR after 1 oct to get eligible for hacktoberfest , I can assign you now, so you can work..

**Comment by memyselfandglitch** [comment]
Sure I shall start now.
