### ISSUE TITLE
Implemetation of Lazy Loading to optimize the performance of the App 

### ISSUE THREAD

**Issue by devDEV03** [mohitahlawat2001/aniSensei#22]

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by devDEV03** [comment]
kindly assign the hacktoberfest tags

**Comment by mohitahlawat2001** [comment]
> i assigned it to you
> 
> > make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

@devDEV03 did you not read this
