### ISSUE TITLE
Improvement in .env Setup Instructions for Firebase and Other API Keys

### ISSUE THREAD

**Issue by ARRY7686** [mohitahlawat2001/aniSensei#3]
Description:

I was recently going through the documentation and noticed that the steps provided for setting up the environment variables (.env file) are missing some important fields, especially for the Firebase integration. While the API keys such as 
```
REACT_APP_FIREBASE_API_KEY,
REACT_APP_TMDB_API_KEY
REACT_APP_GEMINI_API_KEY
```
are mentioned, Firebase typically requires additional fields for full functionality, including:
```
REACT_APP_FIREBASE_PROJECT_ID
REACT_APP_FIREBASE_STORAGE_BUCKET
REACT_APP_FIREBASE_MESSAGING_SENDER_ID
REACT_APP_FIREBASE_APP_ID
REACT_APP_FIREBASE_MEASUREMENT_ID
```
Without these fields, certain Firebase services such as Cloud Messaging, Analytics, and Storage may not work as expected. I'd like to suggest updating the documentation to include these fields, ensuring that users have a smoother experience setting up the environment variables.

Additionally, I would like to contribute to this project as part of my Hacktoberfest participation by fixing this issue. If you're open to it, could you please assign this issue to me? I would be happy to make the necessary updates to the documentation.

Thank you for your time and consideration. I'm excited to contribute!

**Comment by mohitahlawat2001** [comment]
Sure

**Comment by ARRY7686** [comment]
can you pls provide me ur email adress as it is needed in code of conduct
