### ISSUE TITLE
Navbar-improvement

### ISSUE THREAD

**Issue by Vixs101** [mohitahlawat2001/aniSensei#6]
Hi, I'd like to suggest we make improvements to the navbar by making it static and also fixing the icons on the left as the don't look good on the desktop
![image](https://github.com/user-attachments/assets/70d70b08-4af5-4b94-a526-670d65e8aa10)

**Comment by mohitahlawat2001** [comment]
after changing can you post video how it performs

**Comment by Vixs101** [comment]
Alright, thanks. Can you please assign the task to me? so someone doesn't take it

**Comment by Abhi0049k** [comment]
Hi @mohitahlawat2001, Can you this issue to me?

**Comment by Vixs101** [comment]
Hi @mohitahlawat2001 , i have a question about the firebase configuration. how can I get the .env variables? since they'll only be unique to you?
and also can we connect on whatsapp? i also want to discuss another issue i'd like to create too, or may be github discussions?

**Comment by mohitahlawat2001** [comment]
You can use your variable, when upload make .env.example tell name of all
variable there value can be filled by any one using it

**Comment by Vixs101** [comment]
@mohitahlawat2001 sorry i'm still a bit confused. when you create a new firebase project, you will be given the firebase API keys right?
so now that we are trying to collaborate on this project, do I have to create another firebase project in order to get the API keys or are you going to share it? because at the moment, the application won't display anything because of the firebase error.
sorry for the loads of questions

**Comment by mohitahlawat2001** [comment]
Key's can be replaced by any firebase app , you can use your for local development, show variable name in env file ,

**Comment by Vixs101** [comment]
Alright then, thank you so much
