### ISSUE TITLE
show Password Functionality

### ISSUE THREAD

**Issue by lovishGIT** [mohitahlawat2001/aniSensei#9]
We can add a show password functionality in the login and signup page to improve User Experience.

Please Assign me under Hacktoberfest.

**Comment by lovishGIT** [comment]
![image](https://github.com/user-attachments/assets/76f17270-e607-4606-941f-5c6f03c19d30)

**Comment by lovishGIT** [comment]
![image](https://github.com/user-attachments/assets/1a7d6479-c9c3-45e2-9ace-186ef026974a)

**Comment by lovishGIT** [comment]
Can you assign me this issue ???
and please add hacktoberfest.

**Comment by mohitahlawat2001** [comment]
You can start working on this i will assign, you when I start pc again,
Make sure you star ⭐ repo and follow on GitHub
